gh/modules/actions-repo/repo.tf
gh/modules/actions-repo/variables.tf
gh/repos/repos.tf

Adds
- creates new action docs repo (tooling for auto generating docs from action.yml)
- enables dependabot alerts by default
- enabled code owner review requirement by default

chore: add new actions docs repo

---

gh/repos/repos.tf

Provision SSH Action repo. I will add test infra in a follow up PR.

chore: add ssh action repo

---

actions-test-infra/auth/outputs.tf
actions-test-infra/auth/sa.tf
actions-test-infra/auth/secret.tf

small changes from testing in https://github.com/google-github-actions/auth/pull/44

fix: add token creator for JSON creds SA

---

actions-test-infra/get-gke-credentials/outputs.tf
actions-test-infra/get-gke-credentials/wif.tf

test infra for https://github.com/google-github-actions/get-gke-credentials/pull/141

feat: WIF test infra for get-gke-creds

---

actions-test-infra/deploy-appengine/outputs.tf
actions-test-infra/deploy-appengine/wif.tf
actions-test-infra/deploy-cloud-function/outputs.tf
actions-test-infra/deploy-cloud-function/providers.tf
actions-test-infra/deploy-cloud-function/wif.tf
actions-test-infra/deploy-cloudrun/outputs.tf
actions-test-infra/deploy-cloudrun/providers.tf
actions-test-infra/deploy-cloudrun/wif.tf
actions-test-infra/get-secretmanager-secrets/outputs.tf
actions-test-infra/get-secretmanager-secrets/providers.tf
actions-test-infra/get-secretmanager-secrets/wif.tf
actions-test-infra/ssh-compute/outputs.tf
actions-test-infra/ssh-compute/providers.tf
actions-test-infra/ssh-compute/wif.tf
actions-test-infra/upload-cloud-storage/outputs.tf
actions-test-infra/upload-cloud-storage/providers.tf
actions-test-infra/upload-cloud-storage/wif.tf

similar to https://github.com/google-github-actions/test-infra/pull/19 for all actions

feat: WIF infra for all actions

---

actions-test-infra/deploy-cloud-function/outputs.tf
actions-test-infra/deploy-cloud-function/sa.tf
actions-test-infra/deploy-cloud-function/secret.tf
actions-test-infra/get-secretmanager-secrets/secret.tf
gh/repos/repos.tf

I don't have an environment to test this on, but it _looks_ right 😄

Create a secret for use in Cloud Functions

---

actions-test-infra/deploy-cloud-function/secret.tf
actions-test-infra/get-secretmanager-secrets/secret.tf

Looks like I edited the wrong file last night
/cc @bharathkkb

Fix secret manager permissions

---

gh/repos/repos.tf

Noticed that some repo topics had changed out of band, this reconciles them to what was upstream

fix: update repo topics

---

gh/labels/labels.tf

chore: remove unnecessary label

---

gh/modules/actions-repo/repo.tf
gh/repos/repos.tf

Let me know if there is anything is missed, tried to infer from other repos in this file.
gh/modules/actions-repo/repo.tf --> Format only
/cc @bharathkkb @sethvargo

feat: add example workflows

---

actions-test-infra/ssh-compute/compute.tf
actions-test-infra/ssh-compute/outputs.tf
gh/repos/repos.tf

- remove external VM configs for ssh
- reconcile required checks with live state for auth

chore: remove external VM configs for ssh action

---

actions-test-infra/deploy-cloud-function/sa.tf
actions-test-infra/deploy-cloud-function/secret.tf

chore: add service account permissions for GCF integration tests

---

actions-test-infra/get-gke-credentials/cluster.tf
actions-test-infra/get-gke-credentials/outputs.tf
actions-test-infra/get-gke-credentials/providers.tf
actions-test-infra/get-gke-credentials/wif.tf

e2e for https://github.com/google-github-actions/get-gke-credentials/pull/227
Also updated deps to latest.
This has been applied.

feat: add connect gw infra

---

actions-test-infra/deploy-cloudrun/providers.tf
actions-test-infra/deploy-cloudrun/run.tf
actions-test-infra/deploy-cloudrun/wif.tf

Updated terraform and provider versions for test infra for deploy-cloudrun

fix: update tf and provider versions for test-infra deploy-cloudrun

---

actions-test-infra/setup-cloud-sdk/.terraform.lock.hcl
actions-test-infra/setup-cloud-sdk/providers.tf

update provider for tf versions >= 1 (setup-cloud-sdk)

---

gh/repos/repos.tf
gh/repos/test_infra_sources.tf

add actions-utils repo

---

gh/repos/repos.tf

This has already been applied.
We can add test infrastructure after.

add create-cloud-deploy-release repo

---

tools/labeler/main.go

Added repo ignore list and included `release-please-action` as they have custom labels for internal mapping.

add ignore repo list

---

main.tf
project_create-cloud-deploy-release.tf

add cloud deploy resources

---

modules/project/github.tf
project_auth.tf
project_deploy-cloud-functions.tf
project_deploy-cloudrun.tf
project_get-gke-credentials.tf
project_get-secretmanager-secrets.tf
project_ssh-compute.tf
project_upload-cloud-storage.tf

Drop unnecessary secrets

---

modules/project/github.tf
project_analyze-code-security-scc.tf
project_deploy-gke.tf

Fix description and workaround bug for DCO

---

main.tf
project_deploy-gke.tf
project_get-gke-credentials.tf
project_ssh-compute.tf

Closes https://github.com/google-github-actions/test-infra/pull/65
Already applied

Add infra for deploy-gke

---

main.tf
project_deploy-gke.tf
project_get-gke-credentials.tf

Closes https://github.com/google-github-actions/test-infra/pull/67

deploy-gke: grant WIF access to gke clusters

---

main.tf
project_deploy-cloud-functions.tf
project_setup-cloud-sdk.tf

Update new functions infra

---

modules/project/github.tf

fix: update bot permissions

---

project_render-parameter-version.tf

Add render-parameter-version repo (private for now)

---

project_render-parameter-version.tf

Fix collaborators

---

project_render-parameter-version.tf

fix: add permissions for list, get and access parameter and parameter version
